### ISSUE TITLE
Should update() use references?

### ISSUE THREAD

**Issue by smallfly** [musiko/ofxChromaKeyShader#5]
Hi,

Is there any reason why the `void updateChromakeyMask(ofTexture input_tex, ofTexture bg_tex);` method is not using references of the passed ofTextures?

Also, the the textures could be passed by reference-to-const, as this:
`void updateChromakeyMask(const ofTexture& input_tex, const ofTexture& bg_tex);`

What do think of this?

I could send you a PR with those changes.

Cheers.

**Comment by musiko** [comment]
No special reason behind...simply a bad habit in the past :(
Pass by ref-to-const is certainly better, thanks!
Closed by #4
