### ISSUE TITLE
Example Build Fail

### ISSUE THREAD

**Issue by rdtor** [musiko/ofxChromaKeyShader#7]
home/shank/of-workspace/addons/ofxChromaKeyShader/example-with-ofxGui/src/main.cpp:9:14: note: field ‘int ofWindowSettings::height’ can be accessed via ‘int ofWindowSettings::getHeight() const’
     settings.height = 768;
              ^~~~~~
              getHeight()
make[1]: *** [/home/shank/of-workspace/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:217: obj/linux64/Release/src/main.o] Error 1
make[1]: Leaving directory '/home/shank/of-workspace/addons/ofxChromaKeyShader/example-with-ofxGui'
make: *** [/home/shank/of-workspace/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2

**Comment by musiko** [comment]
Fixed by 3eec873
